name: ci-checks

on:
  workflow_call:
    inputs:
      labview-version:
        required: false
        default: "20.0"
        type: string
      ci-container:
        required: false
        default: "ghcr.io/${{ github.repository }}:main"
        type: string

jobs:

  labview-checks:
  
    runs-on: ubuntu-latest

    steps:

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          # cache: 'pip'
          

      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install pylavi
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          uv venv
          uv pip install pylavi

      - name: Run pylavi Tests
        shell: bash
        run: |

          # check if .lvversion file exists and use the workflow inputs labview-version if not
          if [ -f .lvversion ]; then
            # read the LabVIEW version from the first line of .lvversion file
            LV_VERSION="$(head -n 1 .lvversion)"
            # convert to integer
            LV_VERSION=` echo $LV_VERSION | sed 's/\..*//' `
          else
            # use the workflow input labview-version
            LV_VERSION=${{ inputs.labview-version }}
          fi

          source .venv/bin/activate

          # print helpful info
          echo "Verifying:"
          echo "  - Save Version is $LV_VERSION"
          echo "  - Separate Compiled Code"
          echo "  - No Breakpoints"

          # call pylavi
          vi_validate \
            --path source \
            --path tests \
            --gt $LV_VERSION --lt $((LV_VERSION+1)) \
            --skip *.vit \
            --no-code \
            --breakpoints


  doc-checks:

    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    
    runs-on: ubuntu-latest

    env:
      AUTODOC_PY: .github/workflows/auto_doc.py
      AUTODOC_REQUIREMENTS: "xmltodict pydantic"
      AUTODOC_DIR: .auto_doc

    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          # cache: 'pip'


      - name: Checkout Auto-Doc
        uses: actions/checkout@v4
        with:
          repository: 'vipm-io/OpenG-Toolkit'
          ref: 'main'
          path: ${{env.AUTODOC_DIR}}
          sparse-checkout: |
            ${{env.AUTODOC_PY}}
          sparse-checkout-cone-mode: false

      - name: Run auto_doc.py
        run: |
          python -m pip install ${{env.AUTODOC_REQUIREMENTS}}
          mv "${AUTODOC_DIR}/${AUTODOC_PY}" $AUTODOC_PY
          python $AUTODOC_PY
          rm $AUTODOC_PY && rm -rf $AUTODOC_DIR

      - name: Commit and push changes
        uses: devops-infra/action-commit-push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          commit_prefix: "[AUTO-DOC]"
          target_branch: auto-doc-${{github.run_number}}

      - name: Create pull request
        uses: devops-infra/action-pull-request@master
        with:
          source_branch: auto-doc-${{github.run_number}}
          target_branch: ${{ github.ref_name }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          body: "**Automated pull request**<br><br>Documentation has been updated automatically."
          title: auto-doc-${{github.run_number}}


  caraya-tests:

    runs-on:
      - ubuntu-latest

    container:
      image: ${{ inputs.ci-container }}
      credentials:
          username: ${{ github.actor }}
          password: ${{ secrets.github_token }}
      
    steps:
      - uses: actions/checkout@v4    
      
      - name: Caraya Tests
        shell: bash
        run: |
          echo "Applying VIPC Starting Display..."
          start_display ${{ secrets.NGROK_TOKEN }}
          echo "Refreshing Package List..."
          dragon refresh --vipm          
          echo "Applying VIPC file..."
          dragon vipm apply-vipc --labview-version 2024 --labview-bitness 64 --timeout 600 ./source/.vipc
          if [ -f "./build support/coverage.vi" ]; then
            echo "Calculating Test Coverage..."
            g-cli --timeout 600000 "./build support/coverage.vi"
          fi
          echo "Running unit tests..."
          g-cli --timeout 600000 Caraya -- -s "tests" -x "report.xml" -v true -r true
          
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: caraya-test-report
          path: |
            ./report.xml
            ./codecov.json

      - name: Caraya Test Report
        uses: mikepenz/action-junit-report@v4
        if: success() || failure() # always run even if the previous step fails
        with:
          check_name: Caraya Test Report
          report_paths: report.xml

      - run: |
          # these files mess up the codecov report uploader, so remove them
          rm -f report.xml
          rm -f "build support/coverage.vi"

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        env:
          CI: true
        with:
          # fail_ci_if_error: true # optional (default = false)
          # name: codecov-umbrella # optional
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: ${{ github.repository }}
          verbose: true # optional (default = false)
          flags: unittests
          files: "./codecov.json"
